# Default ZombieMod Config file
# 
#  
# 
# debugMode: [true|false] Enable extra debugging messages in server logs.


debugMode: false

blocknaturalspawns: true

dayspawner: true
chunklimit: 6
zombiespawnratio: 75
spawnmultiplier: 1

givezombieplayeritems: true

factionsWildName: wilderness

allowedbreaks:
- STONE
- DIRT
- GRASS
- GRAVEL
- GLASS
- THIN_GLASS
- MYCEL
- SAND
- CACTUS
- CLAY
- LEAVES
- LOG
- SOUL_SAND
- WOOD
- TORCH
- SPONGE
