name: ZombieMod
version: 1.0.1
description: 28 Dead Resident Shaun's of Evil Later.
author: SableDnah
authors: [SableDnah, DarkLust] 
website: http://dev.bukkit.org/server-mods/zombiemod/

main: me.sablednah.zombiemod.ZombieMod
softdepend: [ Spout,Heroes ]

commands:
    zombiemod:
        description: "Root command for all  ZombieMod Commands.
usage| /<command> [reload|spawn|purge]
e.g. /zombiemod spawn rage
or  /zombiemod purge 20"

permissions:
    zombiemod.*:
        description: Players with this node have all ZombieMod permissions.
        default: op
        children:
            zombiemod.reload: true
        
    zombiemod.reload:
        description: Players with this node can use reload command.
        default: op

    zombiemod.spawn:
        description: Players with this node can use spawn command.
        default: op

    zombiemod.purge:
        description: Players with this node can use purge command.
        default: op